import { Geist, Geist_Mono } from "next/font/google";
import ThemeProvider from "./themwProvider";
import AuthRefresh from "@/refreshtoken";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` h-full antialiased w-full`}
      suppressHydrationWarning
    >
      <body className=" h-full flex flex-col">
        <ThemeProvider attribute="class">
          <AuthRefresh />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
